import type { Metadata } from "next";
import SideBar from "@/components/sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster />
      <body className="flex">
        <SideBar>{children}</SideBar>
        {/* <div className="flex-1">{children}</div> */}
      </body>
    </html>
  );
}
